function vhandling ( theVehicle )
    if getElementModel(theVehicle) == 602 then -------------- vehicle Id
        setVehicleHandling(theVehicle, "mass", 1000.0)
		setVehicleHandling(theVehicle, "turnMass", 3000)
		setVehicleHandling(theVehicle, "dragCoeff", 2.0 )
		setVehicleHandling(theVehicle, "centerOfMass", { 0.0,0.0,-0.30 } )
		setVehicleHandling(theVehicle, "percentSubmerged", 50)
		setVehicleHandling(theVehicle, "tractionMultiplier", 1.20)
		setVehicleHandling(theVehicle, "tractionLoss", 0.85)
		setVehicleHandling(theVehicle, "tractionBias", 0.5)
		setVehicleHandling(theVehicle, "numberOfGears", 5)
		setVehicleHandling(theVehicle, "maxVelocity", 200.0)
		setVehicleHandling(theVehicle, "engineAcceleration", 12.0 )
		setVehicleHandling(theVehicle, "engineInertia", 10.0)
		setVehicleHandling(theVehicle, "driveType", "awd")
		setVehicleHandling(theVehicle, "engineType", "petrol")
		setVehicleHandling(theVehicle, "brakeDeceleration", 11.0)
		setVehicleHandling(theVehicle, "brakeBias", 0.45)
		setVehicleHandling(theVehicle, "steeringLock", 30.0 )
		setVehicleHandling(theVehicle, "suspensionForceLevel", 2.60)
		setVehicleHandling(theVehicle, "suspensionDamping", 0.10 )
		setVehicleHandling(theVehicle, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(theVehicle, "suspensionUpperLimit", 0.28 )
		setVehicleHandling(theVehicle, "suspensionLowerLimit", -0.14)
		setVehicleHandling(theVehicle, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(theVehicle, "suspensionAntiDiveMultiplier", 0.4)
		setVehicleHandling(theVehicle, "seatOffsetDistance", 0.25)
		setVehicleHandling(theVehicle, "collisionDamageMultiplier", 1.0)
		setVehicleHandling(theVehicle, "modelFlags", 0x40000000)
		setVehicleHandling(theVehicle, "handlingFlags", 0x00000001)
    end
end
addEventHandler ( "onPlayerVehicleEnter", getRootElement(), vhandling )